#include "Consts.h"

void SetupPins(){
  pinMode(BUTTON_FORWARD, INPUT_PULLUP);
  pinMode(BUTTON_BACKWARD, INPUT_PULLUP);
  pinMode(BUTTON_LEFT, INPUT_PULLUP);
  pinMode(BUTTON_RIGHT, INPUT_PULLUP);
  pinMode(BUTTON_BREAK, INPUT_PULLUP);
  pinMode(BUTTON_STOP, INPUT_PULLUP);
}